[workspace]
resolver = "2"
members = [
  "supervisor",
  "plugins/adder",
  "plugins/subtract",
  "plugins/divide",
  "plugins/multiply",
  "plugins/modulo",
]

# Default members to run with `cargo run`
default-members = ["supervisor"]
